### ISSUE TITLE
Let user enter the money to play

### ISSUE THREAD

**Issue by mayisa87** [brandonshawfhl/Slot-Machine#1]
https://github.com/brandonshawfhl/Slot-Machine/blob/adcfb24dd399c85f53e5e82f62d231b96f0435d0/Slot%20Machine/Program.cs#L11

The user should decide how much money he wants to use to wager. Each run, he will enter a betAmount and by this amount you should then somehow build a logic on which lines to be checked for winning. 1 horizontal line, 2  or all 3. 1 vertical, 2 or 3. There a different ways to implement the logic. 

1. You could e.g. ask user which lines to play first, horizontal vertical or diagnal. And then use 1$ for 1 line , 2 for 2 lines and 3$ for all three.$
2. Another option could be to use the betAmount to figure out the lines to play. 1-3$, horizontal 4-6$ horizontal + vertical 7-8$ hor. + vert. + diagonal So 5$ would check 3 hor. Lines and 2 vertical

**Comment by brandonshawfhl** [comment]
Ok sounds good. I had planned to take care of this I just hadn't gotten to it yet, but I was just going to do horizontals. I will definitely add the other ways of winning and consider the logic ideas you have given me.
