### ISSUE TITLE
Upper boundary not included at random generation

### ISSUE THREAD

**Issue by mayisa87** [brandonshawfhl/Slot-Machine#2]
https://github.com/brandonshawfhl/Slot-Machine/blob/adcfb24dd399c85f53e5e82f62d231b96f0435d0/Slot%20Machine/Program.cs#L23

Remember, if you want to have a random number between 0 and 9 you need to use random.Next(0,9+1);

**Comment by brandonshawfhl** [comment]
I never knew this in the first place, so thank you for letting me know.
