### ISSUE TITLE
betIsNotValid  only set once

### ISSUE THREAD

**Issue by mayisa87** [brandonshawfhl/Slot-Machine#8]
https://github.com/brandonshawfhl/Slot-Machine/blob/e0537753abb1c5f6e204556d191c16f8c9b0d683/Slot%20Machine/Program.cs#L50

The variable for loop condition is never changed inside the loop again, so if loop os entered with betIsNotValid ==true,  you will not leave it again?

**Comment by brandonshawfhl** [comment]
I guess I don't fully understand how boolean variables work. I though I did, but I'm really confused about them and I wasn't able to make sense of them by reading the documentation either.

**Comment by mayisa87** [comment]
![image](https://github.com/brandonshawfhl/Slot-Machine/assets/130921606/59d52f0f-7a7c-4e31-ac87-cb38b1b3f26b)

The usage of your betIsNotValid is, to make the while loop run until there was a valid user input for the bet amount. So first very important thing to know, a boolean variable won't update automatically, so if you use the boolean before the while loop, it will receive whether true or false as value. But it will not update automatically in loop again, so you need to again change the value within the loop

Second thing about your betIsNotValid, to enter the while loop at all (which is not the case currently ;) ) the condition must be true. You initialize moneyCount = 100 and userBet = 1 
So if you go through the parts of your conditions it is like this:
1.) userBet > moneyCount (1>100)  ==> FALSE
2.) userBet<=0 (1 <=0) ==> FALSE

As you use an logical OR (||) one of the conditions needs to be true, so your boolean variable will be set to true too

So to make it enter your loop at least once (so user can enter something at all) there are two options:
1.) Initialize the userBet with a different value to make your condition valid
2.) Initialize your betIsNotValid with true

and in any case, update the variable in your while loop, so the value is updated and at next iteration the variable is checked again if true or false in your loop condition
